### ISSUE TITLE
DMS emissions diagnostic (SFDMS) missing in CAM output 

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm_simulations#31]
**Problem** : The field SFDMS (DMS emission strength) is not available in the output diagnostics from the atmosphere (cam.h0a file).

**Temporary fix** : To still have an impression of the DMS emission strength, one can look at the variable GS_DMS multipied by -1 (GS_DMS indicatesis how much DMS is chemically formed/destroyed).

**Comment by DirkOlivie** [comment]
Some additional thought:

In NorESM2, for all tracers _X_, there was in the cam.h0 output an _SFX_ diagnostic (emission strength).  Even species which had no emissions, had such an output field.  E.g., in NorESM2 the tracers SO4_A1, H2O2, H2SO4, ... had no emissions - so no such output variable should exist in the output to save space - but their zero emissions were still appearing in the cam.h0 file).

In NorESM2.5, only species which actually have non-zero emissions still appear in the output file (good to save space).   Only for DMS this criterium is maybe not applied correctly?

**Comment by oyvindseland** [comment]
It has to be included in one of the categories below. (From chemistry.F90) 

if (has_emis(m) .or. aero_has_emis(solsym(m)) .or. ocean_emis_species(
solsym(m)) .or. srf_emis_diag(n)) then
